version: '3.7'

services:

  # here is our mysql database
  db:
    image: mariadb:latest
    container_name: ${SLUG}_mysql
    volumes:
      - ./db:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_HOST: ${SLUG}_mysql

  # here is our wordpress server
  wordpress:
    depends_on:
      - db
#    image: wordpress:latest
    build:
      context: .
      dockerfile: Docker/Dockerfile
      args:
        SLUG: ${SLUG}
        WORDPRESS_DB_HOST: ${SLUG}_mysql
        WORDPRESS_DB_USER: ${DB_USER:-wordpress}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
        WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-somewordpress}
    container_name: ${SLUG}_wp
    volumes:
      # our persistent local data re routing
      - .:/var/www/html/wp-content/plugins/wp-insert-quote
      - ./confs/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./logs/wp_debug.log:/var/www/html/wp-content/debug.log
    ports:
      - "80:80"
    restart: always
    environment:
      # our local dev environment
      WORDPRESS_DEBUG: ${WP_DEBUG}
      DEVELOPMENT: 1
      # docker wp config settings
      WORDPRESS_DB_HOST: ${SLUG}_mysql
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_AUTH_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_SECURE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_LOGGED_IN_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_NONCE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_SECURE_AUTH_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_LOGGED_IN_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_NONCE_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_CONFIG_EXTRA: |

        /* Development parameters */
        define('WP_CACHE', false);
        define('ENVIRONMENT', 'local');
        define('WP_DEBUG_LOG', ${WP_DEBUG});

        /* Configure mail server */
        define('WORDPRESS_SMTP_AUTH', false);
        define('WORDPRESS_SMTP_SECURE', '');
        define('WORDPRESS_SMTP_HOST', 'mailhog');
        define('WORDPRESS_SMTP_PORT', '1025');
        define('WORDPRESS_SMTP_USERNAME', null);
        define('WORDPRESS_SMTP_PASSWORD', null);
        define('WORDPRESS_SMTP_FROM', 'whoever@example.com');
        define('WORDPRESS_SMTP_FROM_NAME', 'Whoever');

        /* add any more custom wp-config defines here */

  # here is our mail hog server
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${SLUG}_mailhog
    ports:
      - "8025:8025"

  adminer:
    container_name: ${SLUG}_adminer
    image: adminer
    links:
      - db
    ports:
      - 8080:8080

#  wp-cli:
#    container_name: ${SLUG}_wp-cli
#    image: wordpress:cli-php8.2
#    links:
#      - db
#      - wordpress
#    depends_on:
#      - db
#      - wordpress
#    volumes_from:
#      - wordpress:rw
#    #    build:
##      context: .
##      dockerfile: Docker/wp-cli.Dockerfile
#    environment:
#      WORDPRESS_DB_HOST: ${SLUG}_mysql
#      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
#      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
#      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}